### PR TITLE
Extend EPG Module

### PR DESCRIPTION
**Pull request by jgomezve**

### CODE REVIEW

**Comment by danischm** [comment]
Depends on: https://github.com/ciscoecosystem/aci-go-client/pull/252

**Review by danischm — APPROVED** [review]

**Comment by andbyrne** [comment]
This change introduced errors. When active_uplinks_order and/or standby_uplinks are not specified, the code still tries to create the fvUplinkOrderCont object. This fails with the following message:

```
│ Error: Active/Standby configuration empty.
│ 
│   with module.tenant["mgmt"].module.aci_endpoint_group["infra-mgmt/infra-mgmt"].aci_rest_managed.fvUplinkOrderCont["pod1-vds"],
│   on .terraform/modules/tenant.aci_endpoint_group/main.tf line 305, in resource "aci_rest_managed" "fvUplinkOrderCont":
│  305: resource "aci_rest_managed" "fvUplinkOrderCont" {
```

**Comment by jgomezve** [comment]
@andbyrne thanks for raising this. I already create the PR

**Comment by danischm** [comment]
PR is merged and integrated in nac-tenant v0.4.2.

**Pull request merged**
